[plottings]
# plot: matplotlibで描画, 3d: STLファイルに出力
mode = "plot"

# 描画範囲
width   = 512     # 横
height  = 512     # 縦

[parameters]
# paramは、"AABAB"等の文字と、41243等の数値を渡せる
param = "AABBAB"
# 成長の初期値
initX = 0.5
# 反復計算回数
N = 10
# aとbがそれぞれ取り得る最小値と最大値
amin = 0
amax = 4
bmin = 0
bmax = 4
# simple, sin2
func = "simple"
# 定数
const = 2.7